//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TH04.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int ItemId { get; set; }
        public string ItemName { get; set; }
        public int CategoryId { get; set; }
        public decimal ItemPrice { get; set; }
        public string ItemImageName { get; set; }
    
        public virtual CATEGORy CATEGORy { get; set; }
    }
}
